### ISSUE TITLE
Support having a scanner connected to tablet over bluetooth

### ISSUE THREAD

**Issue by sefininio** [markusressel/barcode-server#200]
This is not a feature request, but rather a question or discussion...
I have a BT barcode scanner and the way I'd like to use it is to have it connected to a tablet in the kitchen, and once it scans a barcode, have that barcode transmitted to barcode-server (running as a docker on my server) to publish to mqtt, which will eventually be consumed by HA and add that item to the Grocy shopping list.

Not sure if barcode-scanner is the right tool to use, even though it looks very well written so I'd like to if it makes sense...

Any ideas?

**Comment by markusressel** [comment]
barcode-server expects to be able to directly communicate with the barcode scanner device.

If you intend to have barcode-server running on a different Server than the one your barcode scanner device is connected to, then barcode-server is not the right tool.

If you intend to have the scanner device connected to the same device (server) that barcode-server is running on, it should work. I have no experience with bluetooth based barcode scanners, but given they work the same way USB Dongle scanners work (as a USB HID Keyboard) then barcode-server should be able to receive barcodes from it. You would have to connect the scanner to your server, and pass through the HID device to the docker container, like explained in the README.

**Comment by sefiAtMelio** [comment]
That's what I thought...
Thanks for the reply 😁
