### ISSUE TITLE
M5Stack Core MP135 Barcode Scanning Station

### ISSUE THREAD

**Issue by troyweber** [markusressel/barcode-server#237]
Your project is awesome and I have it running on this little single-core ARM PC:
https://shop.m5stack.com/products/m5stack-coremp135-w-stm32mp135d

The M5 Stack MP135 has a built-in 2.0" touch screen that is available as a framebuffer device. I want to build on top of what you have done and add a nice UI. The use case is manufacturing and I want to have the users scan a lot number to associate other MQTT events to that lot until the next lot is scanned. This gives a minimal footprint to the shop. I wanted a UI so that I can give the user an "undo" button, as sometimes there are multiple barcode labels in close proximity. My thought being, send an "undo" MQTT message when the button is clicked, and my subscribing application would discard the most recent barcode message. The UI would also show the most recent scanned message of course. Other ideas would be network and broker connection status icons. 

I have very little experience in this area, but what better time to learn? I am curious if you have considered anything like this yourself, and if you recommend anything for the GUI development? This is my current thought: https://pygame-gui.readthedocs.io/en/latest/index.html

Thanks again for the bugfix!

**Comment by markusressel** [comment]
Hi, glad to hear you like the project 😎 

I don't have any experience with building UI applications using python though, so I cannot give any advice.

Since this is also pretty off topic for this repository, I will close this issue. If you have anything else regarding Barcode-Server, feel free to open another issue. Thx!
