### ISSUE TITLE
Using Docker Container on ARM Device

### ISSUE THREAD

**Issue by e316** [markusressel/barcode-server#57]
I am trying to install this on a raspberry pi device running ubuntu arm and have tried on Raspberry os but the docker is failing because it says wrong server type and it wants a regular ubuntu server. How do I get around this limitation.

Thanks

**Comment by markusressel** [comment]
The docker image which is currently provided does only work on x86 hardware.
It would be a good idea to provide multiple images for different platforms though, I will look into that.
If you want to use the docker container on arm now, you have to build it yourself on that platform.
Alternatively you can always use the "native" install method, which should work regardless of the system architecture.

**Comment by markusressel** [comment]
I just did a quick test on a Raspberry Pi 4.
barcode-server works fine when using the native installation variant:

```
> ~/.local/bin/barcode-server run
2021-07-01 22:49:57,567 - barcode_server.cli - INFO - Starting statistics webserver...
2021-07-01 22:49:57,578 - barcode_server.webserver - DEBUG - Starting notifier: http
2021-07-01 22:49:57,578 - barcode_server.webserver - DEBUG - Starting notifier: mqtt
2021-07-01 22:49:57,579 - barcode_server.webserver - INFO - Starting webserver on 127.0.0.1:9654 ...
^C2021-07-01 22:50:04,955 - barcode_server.cli - INFO - Exiting...
> uname -a
Linux 3DPrinter 5.10.39-1-MANJARO-ARM #1 SMP PREEMPT Tue May 25 13:34:54 UTC 2021 aarch64 GNU/Linux
> lscpu
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               ARM
  Model name:            Cortex-A72
    Model:               3
    Thread(s) per core:  1
    Core(s) per cluster: 4
    Socket(s):           -
    Cluster(s):          1
    Stepping:            r0p3
    CPU max MHz:         1500.0000
    CPU min MHz:         600.0000
    BogoMIPS:            108.00
    Flags:               fp asimd evtstrm crc32 cpuid
```

**Comment by markusressel** [comment]
Beginning with release [v2.0.1](https://github.com/markusressel/barcode-server/releases/tag/v2.0.1) the released docker images are compatible with both `linux/amd64` as well as `linux/arm64`. Due to the limited platform compatibility of [orjson](https://github.com/ijl/orjson) other platforms are not supported (and probably wont be anytime soon).
