### ISSUE TITLE
"dead" delay after a scan

### ISSUE THREAD

**Issue by denisvic** [markusressel/barcode-server#61]
To avoid certain mistakes, include a parameter allowing to add a delay (5 seconds for example) after a scan during which a possible duplicate scan would not be interpreted.

**Comment by markusressel** [comment]
Thx for the suggestion, although I am not sure such a feature should be part of this project.

From my (limited) point of view, such a delay would better be implemented on the client side, where it would also be possible to create more complex logic around such a delay. Maybe adding a unique Event ID and the barcode-server ID to each event JSON would suffice.
